/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_prolib_JWQuik_Driver_Trade */

namespace jwquik {

#ifndef _Included_ru_prolib_JWQuik_Driver_Trade
#define _Included_ru_prolib_JWQuik_Driver_Trade
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_prolib_JWQuik_Driver_Trade
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ru_prolib_JWQuik_Driver_00024Trade_init
  (JNIEnv *, jobject);

/*
 * Class:     ru_prolib_JWQuik_Driver_Trade
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ru_prolib_JWQuik_Driver_00024Trade_release
  (JNIEnv *, jobject);

/*
 * Class:     ru_prolib_JWQuik_Driver_Trade
 * Method:    getDate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ru_prolib_JWQuik_Driver_00024Trade_getDate
  (JNIEnv *, jobject);

/*
 * Class:     ru_prolib_JWQuik_Driver_Trade
 * Method:    getSettleDate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ru_prolib_JWQuik_Driver_00024Trade_getSettleDate
  (JNIEnv *, jobject);

/*
 * Class:     ru_prolib_JWQuik_Driver_Trade
 * Method:    getTime
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ru_prolib_JWQuik_Driver_00024Trade_getTime
  (JNIEnv *, jobject);

/*
 * Class:     ru_prolib_JWQuik_Driver_Trade
 * Method:    isMarginal
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ru_prolib_JWQuik_Driver_00024Trade_isMarginal
  (JNIEnv *, jobject);

/*
 * Class:     ru_prolib_JWQuik_Driver_Trade
 * Method:    getAccruedInt
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ru_prolib_JWQuik_Driver_00024Trade_getAccruedInt
  (JNIEnv *, jobject);

/*
 * Class:     ru_prolib_JWQuik_Driver_Trade
 * Method:    getYield
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ru_prolib_JWQuik_Driver_00024Trade_getYield
  (JNIEnv *, jobject);

/*
 * Class:     ru_prolib_JWQuik_Driver_Trade
 * Method:    getTsCommission
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ru_prolib_JWQuik_Driver_00024Trade_getTsCommission
  (JNIEnv *, jobject);

/*
 * Class:     ru_prolib_JWQuik_Driver_Trade
 * Method:    getClearingCenterCommission
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ru_prolib_JWQuik_Driver_00024Trade_getClearingCenterCommission
  (JNIEnv *, jobject);

/*
 * Class:     ru_prolib_JWQuik_Driver_Trade
 * Method:    getExchangeCommission
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ru_prolib_JWQuik_Driver_00024Trade_getExchangeCommission
  (JNIEnv *, jobject);

/*
 * Class:     ru_prolib_JWQuik_Driver_Trade
 * Method:    getTradingSystemCommission
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ru_prolib_JWQuik_Driver_00024Trade_getTradingSystemCommission
  (JNIEnv *, jobject);

/*
 * Class:     ru_prolib_JWQuik_Driver_Trade
 * Method:    getPrice2
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ru_prolib_JWQuik_Driver_00024Trade_getPrice2
  (JNIEnv *, jobject);

/*
 * Class:     ru_prolib_JWQuik_Driver_Trade
 * Method:    getRepoRate
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ru_prolib_JWQuik_Driver_00024Trade_getRepoRate
  (JNIEnv *, jobject);

/*
 * Class:     ru_prolib_JWQuik_Driver_Trade
 * Method:    getRepoValue
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ru_prolib_JWQuik_Driver_00024Trade_getRepoValue
  (JNIEnv *, jobject);

/*
 * Class:     ru_prolib_JWQuik_Driver_Trade
 * Method:    getRepo2Value
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ru_prolib_JWQuik_Driver_00024Trade_getRepo2Value
  (JNIEnv *, jobject);

/*
 * Class:     ru_prolib_JWQuik_Driver_Trade
 * Method:    getAccruedInt2
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ru_prolib_JWQuik_Driver_00024Trade_getAccruedInt2
  (JNIEnv *, jobject);

/*
 * Class:     ru_prolib_JWQuik_Driver_Trade
 * Method:    getRepoTerm
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ru_prolib_JWQuik_Driver_00024Trade_getRepoTerm
  (JNIEnv *, jobject);

/*
 * Class:     ru_prolib_JWQuik_Driver_Trade
 * Method:    getStartDiscount
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ru_prolib_JWQuik_Driver_00024Trade_getStartDiscount
  (JNIEnv *, jobject);

/*
 * Class:     ru_prolib_JWQuik_Driver_Trade
 * Method:    getLowerDiscount
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ru_prolib_JWQuik_Driver_00024Trade_getLowerDiscount
  (JNIEnv *, jobject);

/*
 * Class:     ru_prolib_JWQuik_Driver_Trade
 * Method:    getUpperDiscount
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ru_prolib_JWQuik_Driver_00024Trade_getUpperDiscount
  (JNIEnv *, jobject);

/*
 * Class:     ru_prolib_JWQuik_Driver_Trade
 * Method:    getBlockSecurities
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ru_prolib_JWQuik_Driver_00024Trade_getBlockSecurities
  (JNIEnv *, jobject);

/*
 * Class:     ru_prolib_JWQuik_Driver_Trade
 * Method:    getCurrency
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ru_prolib_JWQuik_Driver_00024Trade_getCurrency
  (JNIEnv *, jobject);

/*
 * Class:     ru_prolib_JWQuik_Driver_Trade
 * Method:    getSettleCurrency
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ru_prolib_JWQuik_Driver_00024Trade_getSettleCurrency
  (JNIEnv *, jobject);

/*
 * Class:     ru_prolib_JWQuik_Driver_Trade
 * Method:    getSettleCode
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ru_prolib_JWQuik_Driver_00024Trade_getSettleCode
  (JNIEnv *, jobject);

/*
 * Class:     ru_prolib_JWQuik_Driver_Trade
 * Method:    getAccount
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ru_prolib_JWQuik_Driver_00024Trade_getAccount
  (JNIEnv *, jobject);

/*
 * Class:     ru_prolib_JWQuik_Driver_Trade
 * Method:    getBrokerRef
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ru_prolib_JWQuik_Driver_00024Trade_getBrokerRef
  (JNIEnv *, jobject);

/*
 * Class:     ru_prolib_JWQuik_Driver_Trade
 * Method:    getClientCode
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ru_prolib_JWQuik_Driver_00024Trade_getClientCode
  (JNIEnv *, jobject);

/*
 * Class:     ru_prolib_JWQuik_Driver_Trade
 * Method:    getUserId
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ru_prolib_JWQuik_Driver_00024Trade_getUserId
  (JNIEnv *, jobject);

/*
 * Class:     ru_prolib_JWQuik_Driver_Trade
 * Method:    getFirmId
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ru_prolib_JWQuik_Driver_00024Trade_getFirmId
  (JNIEnv *, jobject);

/*
 * Class:     ru_prolib_JWQuik_Driver_Trade
 * Method:    getPartnerFirmId
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ru_prolib_JWQuik_Driver_00024Trade_getPartnerFirmId
  (JNIEnv *, jobject);

/*
 * Class:     ru_prolib_JWQuik_Driver_Trade
 * Method:    getExchangeCode
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ru_prolib_JWQuik_Driver_00024Trade_getExchangeCode
  (JNIEnv *, jobject);

/*
 * Class:     ru_prolib_JWQuik_Driver_Trade
 * Method:    getStationId
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ru_prolib_JWQuik_Driver_00024Trade_getStationId
  (JNIEnv *, jobject);

/*
 * Class:     ru_prolib_JWQuik_Driver_Trade
 * Method:    getNumber
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ru_prolib_JWQuik_Driver_00024Trade_getNumber
  (JNIEnv *, jobject);

/*
 * Class:     ru_prolib_JWQuik_Driver_Trade
 * Method:    getOrderNumber
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ru_prolib_JWQuik_Driver_00024Trade_getOrderNumber
  (JNIEnv *, jobject);

/*
 * Class:     ru_prolib_JWQuik_Driver_Trade
 * Method:    getClassCode
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ru_prolib_JWQuik_Driver_00024Trade_getClassCode
  (JNIEnv *, jobject);

/*
 * Class:     ru_prolib_JWQuik_Driver_Trade
 * Method:    getSecCode
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ru_prolib_JWQuik_Driver_00024Trade_getSecCode
  (JNIEnv *, jobject);

/*
 * Class:     ru_prolib_JWQuik_Driver_Trade
 * Method:    getPrice
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ru_prolib_JWQuik_Driver_00024Trade_getPrice
  (JNIEnv *, jobject);

/*
 * Class:     ru_prolib_JWQuik_Driver_Trade
 * Method:    getQty
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ru_prolib_JWQuik_Driver_00024Trade_getQty
  (JNIEnv *, jobject);

/*
 * Class:     ru_prolib_JWQuik_Driver_Trade
 * Method:    isSell
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ru_prolib_JWQuik_Driver_00024Trade_isSell
  (JNIEnv *, jobject);

/*
 * Class:     ru_prolib_JWQuik_Driver_Trade
 * Method:    getValue
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ru_prolib_JWQuik_Driver_00024Trade_getValue
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif

} // end namespace jwquik
