/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_prolib_JWQuik_Driver */

namespace jwquik {

#ifndef _Included_ru_prolib_JWQuik_Driver
#define _Included_ru_prolib_JWQuik_Driver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_prolib_JWQuik_Driver
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ru_prolib_JWQuik_Driver_init__
  (JNIEnv *, jobject);

/*
 * Class:     ru_prolib_JWQuik_Driver
 * Method:    init
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ru_prolib_JWQuik_Driver_init__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ru_prolib_JWQuik_Driver
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ru_prolib_JWQuik_Driver_release
  (JNIEnv *, jobject);

/*
 * Class:     ru_prolib_JWQuik_Driver
 * Method:    setAsyncMode
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ru_prolib_JWQuik_Driver_setAsyncMode
  (JNIEnv *, jobject);

/*
 * Class:     ru_prolib_JWQuik_Driver
 * Method:    setSyncMode
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ru_prolib_JWQuik_Driver_setSyncMode
  (JNIEnv *, jobject);

/*
 * Class:     ru_prolib_JWQuik_Driver
 * Method:    isSyncMode
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ru_prolib_JWQuik_Driver_isSyncMode
  (JNIEnv *, jobject);

/*
 * Class:     ru_prolib_JWQuik_Driver
 * Method:    isAsyncMode
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ru_prolib_JWQuik_Driver_isAsyncMode
  (JNIEnv *, jobject);

/*
 * Class:     ru_prolib_JWQuik_Driver
 * Method:    connect
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ru_prolib_JWQuik_Driver_connect
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ru_prolib_JWQuik_Driver
 * Method:    disconnect
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ru_prolib_JWQuik_Driver_disconnect
  (JNIEnv *, jobject);

/*
 * Class:     ru_prolib_JWQuik_Driver
 * Method:    isQuikConnected
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ru_prolib_JWQuik_Driver_isQuikConnected
  (JNIEnv *, jobject);

/*
 * Class:     ru_prolib_JWQuik_Driver
 * Method:    isDllConnected
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ru_prolib_JWQuik_Driver_isDllConnected
  (JNIEnv *, jobject);

/*
 * Class:     ru_prolib_JWQuik_Driver
 * Method:    sendSyncTransaction
 * Signature: (Ljava/lang/String;)Lru/prolib/JWQuik/ITransactionResult;
 */
JNIEXPORT jobject JNICALL Java_ru_prolib_JWQuik_Driver_sendSyncTransaction
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ru_prolib_JWQuik_Driver
 * Method:    sendAsyncTransaction
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ru_prolib_JWQuik_Driver_sendAsyncTransaction
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif

} // end namespace jwquik
