/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_prolib_JWQuik_CallbackStub */

namespace jwquik {

#ifndef _Included_ru_prolib_JWQuik_CallbackStub
#define _Included_ru_prolib_JWQuik_CallbackStub
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_prolib_JWQuik_CallbackStub
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ru_prolib_JWQuik_CallbackStub_init
  (JNIEnv *, jobject);

/*
 * Class:     ru_prolib_JWQuik_CallbackStub
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ru_prolib_JWQuik_CallbackStub_release
  (JNIEnv *, jobject);

/*
 * Class:     ru_prolib_JWQuik_CallbackStub
 * Method:    onConnectionStatus
 * Signature: (JJLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_ru_prolib_JWQuik_CallbackStub_onConnectionStatus
  (JNIEnv *, jobject, jlong, jlong, jstring);

/*
 * Class:     ru_prolib_JWQuik_CallbackStub
 * Method:    onOrderStatus
 * Signature: (JLru/prolib/JWQuik/IOrder;)V
 */
JNIEXPORT void JNICALL Java_ru_prolib_JWQuik_CallbackStub_onOrderStatus
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     ru_prolib_JWQuik_CallbackStub
 * Method:    onTradeStatus
 * Signature: (JLru/prolib/JWQuik/ITrade;)V
 */
JNIEXPORT void JNICALL Java_ru_prolib_JWQuik_CallbackStub_onTradeStatus
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     ru_prolib_JWQuik_CallbackStub
 * Method:    onTransactionReply
 * Signature: (JJLru/prolib/JWQuik/ITransactionResult;)V
 */
JNIEXPORT void JNICALL Java_ru_prolib_JWQuik_CallbackStub_onTransactionReply
  (JNIEnv *, jobject, jlong, jlong, jobject);

#ifdef __cplusplus
}
#endif
#endif

} // end namespace jwquik
