/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_prolib_JWQuik_Driver_Order */

namespace jwquik {

#ifndef _Included_ru_prolib_JWQuik_Driver_Order
#define _Included_ru_prolib_JWQuik_Driver_Order
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_prolib_JWQuik_Driver_Order
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ru_prolib_JWQuik_Driver_00024Order_init
  (JNIEnv *, jobject);

/*
 * Class:     ru_prolib_JWQuik_Driver_Order
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ru_prolib_JWQuik_Driver_00024Order_release
  (JNIEnv *, jobject);

/*
 * Class:     ru_prolib_JWQuik_Driver_Order
 * Method:    getQty
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ru_prolib_JWQuik_Driver_00024Order_getQty
  (JNIEnv *, jobject);

/*
 * Class:     ru_prolib_JWQuik_Driver_Order
 * Method:    getDate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ru_prolib_JWQuik_Driver_00024Order_getDate
  (JNIEnv *, jobject);

/*
 * Class:     ru_prolib_JWQuik_Driver_Order
 * Method:    getTime
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ru_prolib_JWQuik_Driver_00024Order_getTime
  (JNIEnv *, jobject);

/*
 * Class:     ru_prolib_JWQuik_Driver_Order
 * Method:    getActivationTime
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ru_prolib_JWQuik_Driver_00024Order_getActivationTime
  (JNIEnv *, jobject);

/*
 * Class:     ru_prolib_JWQuik_Driver_Order
 * Method:    getWithdrawTime
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ru_prolib_JWQuik_Driver_00024Order_getWithdrawTime
  (JNIEnv *, jobject);

/*
 * Class:     ru_prolib_JWQuik_Driver_Order
 * Method:    getExpiry
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ru_prolib_JWQuik_Driver_00024Order_getExpiry
  (JNIEnv *, jobject);

/*
 * Class:     ru_prolib_JWQuik_Driver_Order
 * Method:    getAccruedInt
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ru_prolib_JWQuik_Driver_00024Order_getAccruedInt
  (JNIEnv *, jobject);

/*
 * Class:     ru_prolib_JWQuik_Driver_Order
 * Method:    getYield
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ru_prolib_JWQuik_Driver_00024Order_getYield
  (JNIEnv *, jobject);

/*
 * Class:     ru_prolib_JWQuik_Driver_Order
 * Method:    getUID
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ru_prolib_JWQuik_Driver_00024Order_getUID
  (JNIEnv *, jobject);

/*
 * Class:     ru_prolib_JWQuik_Driver_Order
 * Method:    getUserId
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ru_prolib_JWQuik_Driver_00024Order_getUserId
  (JNIEnv *, jobject);

/*
 * Class:     ru_prolib_JWQuik_Driver_Order
 * Method:    getAccount
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ru_prolib_JWQuik_Driver_00024Order_getAccount
  (JNIEnv *, jobject);

/*
 * Class:     ru_prolib_JWQuik_Driver_Order
 * Method:    getBrokerRef
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ru_prolib_JWQuik_Driver_00024Order_getBrokerRef
  (JNIEnv *, jobject);

/*
 * Class:     ru_prolib_JWQuik_Driver_Order
 * Method:    getClientCode
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ru_prolib_JWQuik_Driver_00024Order_getClientCode
  (JNIEnv *, jobject);

/*
 * Class:     ru_prolib_JWQuik_Driver_Order
 * Method:    getFirmId
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ru_prolib_JWQuik_Driver_00024Order_getFirmId
  (JNIEnv *, jobject);

/*
 * Class:     ru_prolib_JWQuik_Driver_Order
 * Method:    getTransId
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ru_prolib_JWQuik_Driver_00024Order_getTransId
  (JNIEnv *, jobject);

/*
 * Class:     ru_prolib_JWQuik_Driver_Order
 * Method:    getNumber
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ru_prolib_JWQuik_Driver_00024Order_getNumber
  (JNIEnv *, jobject);

/*
 * Class:     ru_prolib_JWQuik_Driver_Order
 * Method:    getClassCode
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ru_prolib_JWQuik_Driver_00024Order_getClassCode
  (JNIEnv *, jobject);

/*
 * Class:     ru_prolib_JWQuik_Driver_Order
 * Method:    getSecCode
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ru_prolib_JWQuik_Driver_00024Order_getSecCode
  (JNIEnv *, jobject);

/*
 * Class:     ru_prolib_JWQuik_Driver_Order
 * Method:    getPrice
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ru_prolib_JWQuik_Driver_00024Order_getPrice
  (JNIEnv *, jobject);

/*
 * Class:     ru_prolib_JWQuik_Driver_Order
 * Method:    getBalance
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ru_prolib_JWQuik_Driver_00024Order_getBalance
  (JNIEnv *, jobject);

/*
 * Class:     ru_prolib_JWQuik_Driver_Order
 * Method:    getValue
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_ru_prolib_JWQuik_Driver_00024Order_getValue
  (JNIEnv *, jobject);

/*
 * Class:     ru_prolib_JWQuik_Driver_Order
 * Method:    isSell
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_ru_prolib_JWQuik_Driver_00024Order_isSell
  (JNIEnv *, jobject);

/*
 * Class:     ru_prolib_JWQuik_Driver_Order
 * Method:    getStatus
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_ru_prolib_JWQuik_Driver_00024Order_getStatus
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif

} // end namespace jwquik
