/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.prolib.aquila.JQTrans;

public class JQTransServer {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected JQTransServer(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(JQTransServer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JQTransJNI.delete_JQTransServer(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public JQTransServer(JQTransHandler handler) throws Exception {
    this(JQTransJNI.new_JQTransServer(JQTransHandler.getCPtr(handler), handler), true);
  }

  public void connect(String connParam) throws Exception {
    JQTransJNI.JQTransServer_connect(swigCPtr, this, connParam);
  }

  public void disconnect() throws Exception {
    JQTransJNI.JQTransServer_disconnect(swigCPtr, this);
  }

  public void send(String transactionString) throws Exception {
    JQTransJNI.JQTransServer_send(swigCPtr, this, transactionString);
  }

  public boolean isDllConnected() {
    return JQTransJNI.JQTransServer_isDllConnected(swigCPtr, this);
  }

  public boolean isQuikConnected() {
    return JQTransJNI.JQTransServer_isQuikConnected(swigCPtr, this);
  }

  public String getOrderAccount(long orderDescriptor) {
    return JQTransJNI.JQTransServer_getOrderAccount(swigCPtr, this, orderDescriptor);
  }

  public String getOrderClientCode(long orderDescriptor) {
    return JQTransJNI.JQTransServer_getOrderClientCode(swigCPtr, this, orderDescriptor);
  }

  public String getOrderFirmId(long orderDescriptor) {
    return JQTransJNI.JQTransServer_getOrderFirmId(swigCPtr, this, orderDescriptor);
  }

  public long getOrderQty(long orderDescriptor) {
    return JQTransJNI.JQTransServer_getOrderQty(swigCPtr, this, orderDescriptor);
  }

  public long getOrderDate(long orderDescriptor) {
    return JQTransJNI.JQTransServer_getOrderDate(swigCPtr, this, orderDescriptor);
  }

  public long getOrderTime(long orderDescriptor) {
    return JQTransJNI.JQTransServer_getOrderTime(swigCPtr, this, orderDescriptor);
  }

  public long getOrderActivationTime(long orderDescriptor) {
    return JQTransJNI.JQTransServer_getOrderActivationTime(swigCPtr, this, orderDescriptor);
  }

  public long getOrderWithdrawTime(long orderDescriptor) {
    return JQTransJNI.JQTransServer_getOrderWithdrawTime(swigCPtr, this, orderDescriptor);
  }

  public long getOrderExpiry(long orderDescriptor) {
    return JQTransJNI.JQTransServer_getOrderExpiry(swigCPtr, this, orderDescriptor);
  }

  public double getOrderAccruedInt(long orderDescriptor) {
    return JQTransJNI.JQTransServer_getOrderAccruedInt(swigCPtr, this, orderDescriptor);
  }

  public double getOrderYield(long orderDescriptor) {
    return JQTransJNI.JQTransServer_getOrderYield(swigCPtr, this, orderDescriptor);
  }

  public long getOrderUid(long orderDescriptor) {
    return JQTransJNI.JQTransServer_getOrderUid(swigCPtr, this, orderDescriptor);
  }

  public String getOrderUserId(long orderDescriptor) {
    return JQTransJNI.JQTransServer_getOrderUserId(swigCPtr, this, orderDescriptor);
  }

  public String getOrderBrokerRef(long orderDescriptor) {
    return JQTransJNI.JQTransServer_getOrderBrokerRef(swigCPtr, this, orderDescriptor);
  }

  public long getTradeDate(long tradeDescriptor) {
    return JQTransJNI.JQTransServer_getTradeDate(swigCPtr, this, tradeDescriptor);
  }

  public long getTradeSettleDate(long tradeDescriptor) {
    return JQTransJNI.JQTransServer_getTradeSettleDate(swigCPtr, this, tradeDescriptor);
  }

  public long getTradeTime(long tradeDescriptor) {
    return JQTransJNI.JQTransServer_getTradeTime(swigCPtr, this, tradeDescriptor);
  }

  public boolean getTradeIsMarginal(long tradeDescriptor) {
    return JQTransJNI.JQTransServer_getTradeIsMarginal(swigCPtr, this, tradeDescriptor);
  }

  public double getTradeAccruedInt(long tradeDescriptor) {
    return JQTransJNI.JQTransServer_getTradeAccruedInt(swigCPtr, this, tradeDescriptor);
  }

  public double getTradeYield(long tradeDescriptor) {
    return JQTransJNI.JQTransServer_getTradeYield(swigCPtr, this, tradeDescriptor);
  }

  public double getTradeTsCommission(long tradeDescriptor) {
    return JQTransJNI.JQTransServer_getTradeTsCommission(swigCPtr, this, tradeDescriptor);
  }

  public double getTradeClearingCenterCommission(long tradeDescriptor) {
    return JQTransJNI.JQTransServer_getTradeClearingCenterCommission(swigCPtr, this, tradeDescriptor);
  }

  public double getTradeExchangeCommission(long tradeDescriptor) {
    return JQTransJNI.JQTransServer_getTradeExchangeCommission(swigCPtr, this, tradeDescriptor);
  }

  public double getTradeTradingSystemCommission(long tradeDescriptor) {
    return JQTransJNI.JQTransServer_getTradeTradingSystemCommission(swigCPtr, this, tradeDescriptor);
  }

  public double getTradePrice2(long tradeDescriptor) {
    return JQTransJNI.JQTransServer_getTradePrice2(swigCPtr, this, tradeDescriptor);
  }

  public double getTradeRepoRate(long tradeDescriptor) {
    return JQTransJNI.JQTransServer_getTradeRepoRate(swigCPtr, this, tradeDescriptor);
  }

  public double getTradeRepoValue(long tradeDescriptor) {
    return JQTransJNI.JQTransServer_getTradeRepoValue(swigCPtr, this, tradeDescriptor);
  }

  public double getTradeRepo2Value(long tradeDescriptor) {
    return JQTransJNI.JQTransServer_getTradeRepo2Value(swigCPtr, this, tradeDescriptor);
  }

  public double getTradeAccruedInt2(long tradeDescriptor) {
    return JQTransJNI.JQTransServer_getTradeAccruedInt2(swigCPtr, this, tradeDescriptor);
  }

  public int getTradeRepoTerm(long tradeDescriptor) {
    return JQTransJNI.JQTransServer_getTradeRepoTerm(swigCPtr, this, tradeDescriptor);
  }

  public double getTradeStartDiscount(long tradeDescriptor) {
    return JQTransJNI.JQTransServer_getTradeStartDiscount(swigCPtr, this, tradeDescriptor);
  }

  public double getTradeLowerDiscount(long tradeDescriptor) {
    return JQTransJNI.JQTransServer_getTradeLowerDiscount(swigCPtr, this, tradeDescriptor);
  }

  public double getTradeUpperDiscount(long tradeDescriptor) {
    return JQTransJNI.JQTransServer_getTradeUpperDiscount(swigCPtr, this, tradeDescriptor);
  }

  public boolean getTradeBlockSecurities(long tradeDescriptor) {
    return JQTransJNI.JQTransServer_getTradeBlockSecurities(swigCPtr, this, tradeDescriptor);
  }

  public String getTradeCurrency(long tradeDescriptor) {
    return JQTransJNI.JQTransServer_getTradeCurrency(swigCPtr, this, tradeDescriptor);
  }

  public String getTradeSettleCurrency(long tradeDescriptor) {
    return JQTransJNI.JQTransServer_getTradeSettleCurrency(swigCPtr, this, tradeDescriptor);
  }

  public String getTradeSettleCode(long tradeDescriptor) {
    return JQTransJNI.JQTransServer_getTradeSettleCode(swigCPtr, this, tradeDescriptor);
  }

  public String getTradeAccount(long tradeDescriptor) {
    return JQTransJNI.JQTransServer_getTradeAccount(swigCPtr, this, tradeDescriptor);
  }

  public String getTradeBrokerRef(long tradeDescriptor) {
    return JQTransJNI.JQTransServer_getTradeBrokerRef(swigCPtr, this, tradeDescriptor);
  }

  public String getTradeClientCode(long tradeDescriptor) {
    return JQTransJNI.JQTransServer_getTradeClientCode(swigCPtr, this, tradeDescriptor);
  }

  public String getTradeUserId(long tradeDescriptor) {
    return JQTransJNI.JQTransServer_getTradeUserId(swigCPtr, this, tradeDescriptor);
  }

  public String getTradeFirmId(long tradeDescriptor) {
    return JQTransJNI.JQTransServer_getTradeFirmId(swigCPtr, this, tradeDescriptor);
  }

  public String getTradePartnerFirmId(long tradeDescriptor) {
    return JQTransJNI.JQTransServer_getTradePartnerFirmId(swigCPtr, this, tradeDescriptor);
  }

  public String getTradeExchangeCode(long tradeDescriptor) {
    return JQTransJNI.JQTransServer_getTradeExchangeCode(swigCPtr, this, tradeDescriptor);
  }

  public String getTradeStationId(long tradeDescriptor) {
    return JQTransJNI.JQTransServer_getTradeStationId(swigCPtr, this, tradeDescriptor);
  }

}
