/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.prolib.aquila.JQTrans;

public class JQTrans implements JQTransConstants {
  public static String replace_mod(String new_module) {
    return JQTransJNI.replace_mod(new_module);
  }

}
