/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.prolib.aquila.JQTrans;

public interface JQTransConstants {
  public final static String TRANS2QUIK_DLL = JQTransJNI.TRANS2QUIK_DLL_get();
  public final static String CURRENT_DLL = JQTransJNI.CURRENT_DLL_get();
}
