/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.prolib.aquila.JQTrans;

public class QTransTradeStatus {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected QTransTradeStatus(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(QTransTradeStatus obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JQTransJNI.delete_QTransTradeStatus(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMode(int value) {
    JQTransJNI.QTransTradeStatus_mode_set(swigCPtr, this, value);
  }

  public int getMode() {
    return JQTransJNI.QTransTradeStatus_mode_get(swigCPtr, this);
  }

  public void setId(long value) {
    JQTransJNI.QTransTradeStatus_id_set(swigCPtr, this, value);
  }

  public long getId() {
    return JQTransJNI.QTransTradeStatus_id_get(swigCPtr, this);
  }

  public void setOrderId(long value) {
    JQTransJNI.QTransTradeStatus_orderId_set(swigCPtr, this, value);
  }

  public long getOrderId() {
    return JQTransJNI.QTransTradeStatus_orderId_get(swigCPtr, this);
  }

  public void setClassCode(String value) {
    JQTransJNI.QTransTradeStatus_classCode_set(swigCPtr, this, value);
  }

  public String getClassCode() {
    return JQTransJNI.QTransTradeStatus_classCode_get(swigCPtr, this);
  }

  public void setSecCode(String value) {
    JQTransJNI.QTransTradeStatus_secCode_set(swigCPtr, this, value);
  }

  public String getSecCode() {
    return JQTransJNI.QTransTradeStatus_secCode_get(swigCPtr, this);
  }

  public void setPrice(double value) {
    JQTransJNI.QTransTradeStatus_price_set(swigCPtr, this, value);
  }

  public double getPrice() {
    return JQTransJNI.QTransTradeStatus_price_get(swigCPtr, this);
  }

  public void setQty(int value) {
    JQTransJNI.QTransTradeStatus_qty_set(swigCPtr, this, value);
  }

  public int getQty() {
    return JQTransJNI.QTransTradeStatus_qty_get(swigCPtr, this);
  }

  public void setValue(double value) {
    JQTransJNI.QTransTradeStatus_value_set(swigCPtr, this, value);
  }

  public double getValue() {
    return JQTransJNI.QTransTradeStatus_value_get(swigCPtr, this);
  }

  public void setIsSell(boolean value) {
    JQTransJNI.QTransTradeStatus_isSell_set(swigCPtr, this, value);
  }

  public boolean getIsSell() {
    return JQTransJNI.QTransTradeStatus_isSell_get(swigCPtr, this);
  }

  public void setTradeDescriptor(long value) {
    JQTransJNI.QTransTradeStatus_tradeDescriptor_set(swigCPtr, this, value);
  }

  public long getTradeDescriptor() {
    return JQTransJNI.QTransTradeStatus_tradeDescriptor_get(swigCPtr, this);
  }

  public QTransTradeStatus() {
    this(JQTransJNI.new_QTransTradeStatus(), true);
  }

}
