/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package ru.prolib.aquila.JQTrans;

public class QTransOrderStatus {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected QTransOrderStatus(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(QTransOrderStatus obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        JQTransJNI.delete_QTransOrderStatus(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMode(int value) {
    JQTransJNI.QTransOrderStatus_mode_set(swigCPtr, this, value);
  }

  public int getMode() {
    return JQTransJNI.QTransOrderStatus_mode_get(swigCPtr, this);
  }

  public void setTransId(long value) {
    JQTransJNI.QTransOrderStatus_transId_set(swigCPtr, this, value);
  }

  public long getTransId() {
    return JQTransJNI.QTransOrderStatus_transId_get(swigCPtr, this);
  }

  public void setOrderId(long value) {
    JQTransJNI.QTransOrderStatus_orderId_set(swigCPtr, this, value);
  }

  public long getOrderId() {
    return JQTransJNI.QTransOrderStatus_orderId_get(swigCPtr, this);
  }

  public void setClassCode(String value) {
    JQTransJNI.QTransOrderStatus_classCode_set(swigCPtr, this, value);
  }

  public String getClassCode() {
    return JQTransJNI.QTransOrderStatus_classCode_get(swigCPtr, this);
  }

  public void setSecCode(String value) {
    JQTransJNI.QTransOrderStatus_secCode_set(swigCPtr, this, value);
  }

  public String getSecCode() {
    return JQTransJNI.QTransOrderStatus_secCode_get(swigCPtr, this);
  }

  public void setPrice(double value) {
    JQTransJNI.QTransOrderStatus_price_set(swigCPtr, this, value);
  }

  public double getPrice() {
    return JQTransJNI.QTransOrderStatus_price_get(swigCPtr, this);
  }

  public void setBalance(int value) {
    JQTransJNI.QTransOrderStatus_balance_set(swigCPtr, this, value);
  }

  public int getBalance() {
    return JQTransJNI.QTransOrderStatus_balance_get(swigCPtr, this);
  }

  public void setValue(double value) {
    JQTransJNI.QTransOrderStatus_value_set(swigCPtr, this, value);
  }

  public double getValue() {
    return JQTransJNI.QTransOrderStatus_value_get(swigCPtr, this);
  }

  public void setIsSell(boolean value) {
    JQTransJNI.QTransOrderStatus_isSell_set(swigCPtr, this, value);
  }

  public boolean getIsSell() {
    return JQTransJNI.QTransOrderStatus_isSell_get(swigCPtr, this);
  }

  public void setStatus(int value) {
    JQTransJNI.QTransOrderStatus_status_set(swigCPtr, this, value);
  }

  public int getStatus() {
    return JQTransJNI.QTransOrderStatus_status_get(swigCPtr, this);
  }

  public void setOrderDescriptor(long value) {
    JQTransJNI.QTransOrderStatus_orderDescriptor_set(swigCPtr, this, value);
  }

  public long getOrderDescriptor() {
    return JQTransJNI.QTransOrderStatus_orderDescriptor_get(swigCPtr, this);
  }

  public QTransOrderStatus() {
    this(JQTransJNI.new_QTransOrderStatus(), true);
  }

}
