/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.9
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_JQTrans_WRAP_H_
#define SWIG_JQTrans_WRAP_H_

class SwigDirector_JQTransHandler : public aquila::jqtrans::JQTransHandler, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_JQTransHandler(JNIEnv *jenv);
    virtual ~SwigDirector_JQTransHandler();
    virtual void OnConnectionStatus(long connEvent, long errCode, std::string errMsg);
    virtual void OnTransactionReply(long resultCode, long errCode, long replyCode, unsigned long transId, unsigned long orderId, std::string replyMsg);
    virtual void OnOrderStatus(QTransOrderStatus &status);
    virtual void OnTradeStatus(QTransTradeStatus &status);
public:
    bool swig_overrides(int n) {
      return (n < 4 ? swig_override[n] : false);
    }
protected:
    bool swig_override[4];
};


#endif
